language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4'
  - '5.0'
  - '5'
script:
  -  npm run-script test-travis
before_script:
  - npm install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start